### PR TITLE
axi_dw_downsizer: Fix overflow of B forward FIFO

### PR DESCRIPTION
**Pull request by accuminium**
Before this change, `slv_resp_o.aw_ready` could be asserted even though `forward_b_beat_full`.  When that happened, the AW and W beat were not forwarded but dropped in the DWC, and upstream never got a B response for that transaction back.

To fix this, new writes in the *idle* state are only handled if `!forward_b_beat_full`.  For this, the logic handling the *idle* state has been wrapped in a [new `if` statement](https://github.com/pulp-platform/axi/pull/118/files#diff-3601b4c67184ff301f29a4fe12c0d371R699).  (The additional level of indentation confuses GitHub diff.)

### TODO 
- [ ] Changelog entry

### CODE REVIEW

**Comment by bluewww** [comment]
FYI you can just ignore whitespace changes in github diff so it looks quite clear to me
https://github.com/pulp-platform/axi/pull/118/files?diff=split&w=1

**Comment by accuminium** [comment]
> FYI you can just ignore whitespace changes in github diff so it looks quite clear to me
> https://github.com/pulp-platform/axi/pull/118/files?diff=split&w=1

That's useful, thanks!

**Review by suehtamacv — APPROVED** [review]
Sorry for the delay in reviewing this, I missed this PR. 
Thanks for the changes, they look good to me.

**Comment by accuminium** [comment]
I rebased as discussed, and CI is passing --> merging.

**Pull request merged**
