### PR TITLE
add support for vivado xsim and fusesoc

### PR DESCRIPTION
**Pull request by skokvermon**
to run vivado xsim target with fusesoc, first install fusesoc, then
```
mkdir fusesoc
cd fusesoc
fusesoc library add axi git@github.com:skokvermon/axi.git
fusesoc library add common_cells git@github.com:skokvermon/common_cells.git
fusesoc library add common_verification git@github.com:skokvermon/common_verification.git
fusesoc core list
fusesoc run --tool xsim --target sim --no-export pulp-platform.org::axi:0.35.2.dev
```

### CODE REVIEW

**Comment by skokvermon** [comment]
@andreaskurth Please note that fusesoc doesn't support "-" in version number.
"-dev" version suffix must be replaced with ".dev"

**Comment by hossein1387** [comment]
Any plan on when this PR will be merged?

**Comment by micprog** [comment]
requires https://github.com/pulp-platform/common_verification/pull/4

**Comment by thommythomaso** [comment]
Will be implemented in #262. Closed.

**Comment by skokvermon** [comment]
#262 is not working because of wrong ifdef XSIM

**Pull request closed without merging**
