### PR TITLE
WIP: AXI4 Last Level Cache

### PR DESCRIPTION
**Pull request by WRoenninger**
Added AXI4 Last Level Cache
Features: 
- Write back, Read and Write allocate
- Parameterizable in set-associativity, line length and number of blocks
- Adaptive scratch pad memory mapping of individual sets
- Multiple open AXI transactions
- Tag memory initialization BIST
- Flush by user and SPM reconfiguration
- Random replacement
Added Documentation

This PR directly depends on changes from #116 and #115.

### CODE REVIEW

**Comment by WRoenninger** [comment]
Rebased onto current master.

**Comment by WRoenninger** [comment]
Vsim run script for `axi_llc` took on an Intel i7-4790 a little less than 7h to complete.

**Comment by WRoenninger** [comment]
Rebased onto current master for ci fix by #129.

Same ci timeout issue as for #115. Running vsim script for all modules takes around 8h.

**Comment by thommythomaso** [comment]
The AXI4 Last Level Cache (LLC) has been moved to a dedicated repository on pulp-platform: [`axi_llc`](https://github.com/pulp-platform/axi_llc)

**Pull request closed without merging**
