### PR TITLE
Release 0.6

### PR DESCRIPTION
**Pull request by accuminium**
I propose it's time to make the switch to AXI4+ATOPs (atomic operations), since we are now using such AXI buses in Ariane and our multi-cluster PULP systems. This change makes Release 0.6 non-backwards-compatible with Release 0.5, but I have added guidelines in the Readme on how to deal with this. While this will require some adaptions by users of this module, I think the changes are quickly done when following the guidelines.

### Changed
- AXI interfaces now include the `aw_atop` signal. Interfaces, macros, and existing modules and
  TBs in this repository have been updated. The ReadMe has been updated to guide users of this
  repository on how to deal with the `aw_atop` signal.

### Added
- Add AXI atomic operations (ATOPs) filter.

### CODE REVIEW

**Comment by fabianschuiki** [comment]
@accuminium Do you want to wait with merging for the ATOP filter testbench to be done?

**Comment by accuminium** [comment]
Thanks for your reviews!

> @accuminium Do you want to wait with merging for the ATOP filter testbench to be done?

Yes, absolutely. The ATOP filter is essential for guaranteeing proper functioning of the protocol when slaves do not support ATOPs, so I want to be confident that it is working properly. I am working on the TB and will update the branch soon.

**Comment by fabianschuiki** [comment]
> I am working on the TB and will update the branch soon.

Sounds good. I've added the "WIP:" prefix in the meantime.

**Comment by accuminium** [comment]
Alright, I have thoroughly verified the ATOP filter in simulation and have also added it to the synthesis regressions. I fixed a couple of minor problems with synthesis regressions in the process. In the end, I verified the integrity of this branch by running all simulation and synthesis regressions on a clean checkout.

@fabianschuiki May I ask you to re-review the latest changes? In particular, I would like to have your opinion on  https://github.com/pulp-platform/axi/pull/7/commits/5382e36ea4e3045f3e5f4b315f19d6642bca3cca, https://github.com/pulp-platform/axi/pull/7/commits/78ecbbeb213435cd9413c9c34343a9533a735bba, and https://github.com/pulp-platform/axi/pull/7/commits/08841c42da3b4903d0519f4718a90cffb835ff22.

**Comment by accuminium** [comment]
Thanks!

**Pull request merged**
