### PR TITLE
AXI Last Level Cache

### PR DESCRIPTION
**Pull request by luca-valente**
Dear all,
I rebased the LLC by Wolfgang. I kept only the commits related to the `axi_llc`, one commit on the `axi_demux` and one on `axi_test`.
I removed the commits on the `axi_xbar` and `axi_to_mem` as I had the impression that those modules diverged significantly since 2019. 
The LLC's testbench has quite high coverage. I also integrated it in `AlSaqr/HERO` and the Linux boot works as well.

### CODE REVIEW

**Comment by micprog** [comment]
Linking to #33

**Comment by thommythomaso** [comment]
Should the LLC PRs be closed as the IP has been moved?

**Comment by luca-valente** [comment]
Maybe we should wait for the standalone repository to be public. It's fine to me either way. :smile:

**Comment by thommythomaso** [comment]
The AXI4 Last Level Cache (LLC) has been moved to a dedicated repository on pulp-platform: [`axi_llc`](https://github.com/pulp-platform/axi_llc)

**Pull request closed without merging**
